<a href="https://colab.research.google.com/github/ManthanGarg-1234/AIML-CLASSWORK/blob/main/22_July_AIML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pandas Data Structures and Operations

In [60]:
import pandas as pd
data = [1, 2, 3, 4, 5]
series = pd.Series(data)
print(series)

0    1
1    2
2    3
3    4
4    5
dtype: int64

## 1. Creating Pandas Series

Pandas Series are one-dimensional labeled arrays capable of holding any data type (integers, strings, floats, Python objects, etc.). The axis labels are collectively referred to as the index.

### 1.1 From a List of Numbers

In [61]:
import pandas as pd
data = ['a', 'b', 'c', 'd', 'e']
series = pd.Series(data)
print(series)

0    a
1    b
2    c
3    d
4    e
dtype: object

## 2. Creating Pandas DataFrames

Pandas DataFrames are two-dimensional labeled data structures with columns of potentially different types. You can think of them like a spreadsheet or SQL table, or a dictionary of Series objects.

### 2.1 From a Dictionary of Lists (Simple DataFrames)

In [62]:
data = [1, 2, 3, 4, 5]
series = pd.Series(data)
display(series)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [63]:
data = ['a', 'b', 'c', 'd', 'e']
series = pd.Series(data)
display(series)

0    a
1    b
2    c
3    d
4    e
dtype: object

### 1.2 From a List of Strings

In [64]:
import pandas as pd
data = {'a': [1], 'b': [2], 'c': [3], 'd': [4], 'e': [5]}
df = pd.DataFrame(data)
print(df)

   a  b  c  d  e
0  1  2  3  4  5

In [65]:
import pandas as pd
data = {'Name':['Alice','Bob','Charlie'],'Age':[25,30,35]}
df = pd.DataFrame(data)
print(df)

      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35

In [66]:
import pandas as pd
data = {'Calories':[420, 380, 390],'duration':[50, 40, 45]}
df = pd.DataFrame(data, index=["day1","day2","day3"])
print(df)

      Calories  duration
day1       420        50
day2       380        40
day3       390        45

### 2.2 From a Dictionary with Custom Index

 You can specify a custom index for your DataFrame to make rows more meaningful.

## 3. Loading Data from a CSV File

Often, data is stored in external files. CSV (Comma Separated Values) is a common format. Pandas provides `read_csv()` to load data directly into a DataFrame.

To avoid redundant loading, the CSV will be read once and then subsequent operations will use this `df` object.

In [67]:
df_csv = pd.read_csv('sheetdsa.csv')
print("CSV data loaded into 'df_csv' DataFrame.")

CSV data loaded into 'df_csv' DataFrame.

## 4. Exploring Loaded Data

Once data is loaded, it's crucial to inspect its structure, contents, and basic statistics to understand it better. We will use the `df_csv` DataFrame loaded above.

In [68]:
import pandas as pd
df = pd.read_csv('sheetdsa.csv')
print(df)

     Unnamed: 0    Unnamed: 1  Unnamed: 2  \
0           NaN           NaN         NaN
1           NaN           NaN         NaN
2           NaN  Mark as Done         NaN
3           NaN           NaN         NaN
4        ARRAYS          DONE         1.0
...         ...           ...         ...
996         NaN           NaN         NaN
997         NaN           NaN         NaN
998         NaN           NaN         NaN
999         NaN           NaN         NaN
1000        NaN           NaN         NaN

     Do NOT send any edit request to this sheet. Instead, make a copy of your own.  \
0                           DSA Series by Shradha Ma'am
1                                                   NaN
2                                              Question
3                                                   NaN
4                                      Majority Element
...                                                 ...
996                                                 NaN
997                                                 NaN
998                                                 NaN
999                                                 NaN
1000                                                NaN

        Unnamed: 4  Unnamed: 5      Unnamed: 6  \
0              NaN         NaN             NaN
1              NaN         NaN             NaN
2             Link  Difficulty  Video SOLUTION
3              NaN         NaN             NaN
4     Problem Link        Easy   Solution Link
...            ...         ...             ...
996            NaN         NaN             NaN
997            NaN         NaN             NaN
998            NaN         NaN             NaN
999            NaN         NaN             NaN
1000           NaN         NaN             NaN

                                     Unnamed: 7      Unnamed: 8  Unnamed: 9  \
0     Series Link : DSA Series by Shradha Ma'am             NaN         NaN
1                                           NaN             NaN         NaN
2                                     Companies  Pre-requisites         NaN
3                                           NaN             NaN         NaN
4                                 Amazon Google             NaN         NaN
...                                         ...             ...         ...
996                                         NaN             NaN         NaN
997                                         NaN             NaN         NaN
998                                         NaN             NaN         NaN
999                                         NaN             NaN         NaN
1000                                        NaN             NaN         NaN

      ...  Unnamed: 15  Unnamed: 16  Unnamed: 17  Unnamed: 18  Unnamed: 19  \
0     ...          NaN          NaN          NaN          NaN          NaN
1     ...          NaN          NaN          NaN          NaN          NaN
2     ...          NaN          NaN          NaN          NaN          NaN
3     ...          NaN          NaN          NaN          NaN          NaN
4     ...          NaN          NaN          NaN          NaN          NaN
...   ...          ...          ...          ...          ...          ...
996   ...          NaN          NaN          NaN          NaN          NaN
997   ...          NaN          NaN          NaN          NaN          NaN
998   ...          NaN          NaN          NaN          NaN          NaN
999   ...          NaN          NaN          NaN          NaN          NaN
1000  ...          NaN          NaN          NaN          NaN          NaN

      Unnamed: 20  Unnamed: 21  Unnamed: 22  Unnamed: 23  Unnamed: 24
0             NaN          NaN          NaN          NaN          NaN
1             NaN          NaN          NaN          NaN          NaN
2             NaN          NaN          NaN          NaN          NaN
3             NaN          NaN          NaN          NaN          NaN
4             NaN          NaN          NaN          NaN          NaN
...           ...          ...          ...          ...          ...
996           NaN          NaN          NaN          NaN          NaN
997           NaN          NaN          NaN          NaN          NaN
998           NaN          NaN          NaN          NaN          NaN
999           NaN          NaN          NaN          NaN          NaN
1000          NaN          NaN          NaN          NaN          NaN

[1001 rows x 25 columns]

In [69]:
import pandas as pd
df = pd.read_csv('sheetdsa.csv')
print(df.head())
# print(df.head(2))

  Unnamed: 0    Unnamed: 1  Unnamed: 2  \
0        NaN           NaN         NaN
1        NaN           NaN         NaN
2        NaN  Mark as Done         NaN
3        NaN           NaN         NaN
4     ARRAYS          DONE         1.0

  Do NOT send any edit request to this sheet. Instead, make a copy of your own.  \
0                        DSA Series by Shradha Ma'am
1                                                NaN
2                                           Question
3                                                NaN
4                                   Majority Element

     Unnamed: 4  Unnamed: 5      Unnamed: 6  \
0           NaN         NaN             NaN
1           NaN         NaN             NaN
2          Link  Difficulty  Video SOLUTION
3           NaN         NaN             NaN
4  Problem Link        Easy   Solution Link

                                  Unnamed: 7      Unnamed: 8  Unnamed: 9  ...  \
0  Series Link : DSA Series by Shradha Ma'am             NaN         NaN  ...
1                                        NaN             NaN         NaN  ...
2                                  Companies  Pre-requisites         NaN  ...
3                                        NaN             NaN         NaN  ...
4                              Amazon Google             NaN         NaN  ...

   Unnamed: 15  Unnamed: 16  Unnamed: 17  Unnamed: 18  Unnamed: 19  \
0          NaN          NaN          NaN          NaN          NaN
1          NaN          NaN          NaN          NaN          NaN
2          NaN          NaN          NaN          NaN          NaN
3          NaN          NaN          NaN          NaN          NaN
4          NaN          NaN          NaN          NaN          NaN

   Unnamed: 20  Unnamed: 21  Unnamed: 22  Unnamed: 23  Unnamed: 24
0          NaN          NaN          NaN          NaN          NaN
1          NaN          NaN          NaN          NaN          NaN
2          NaN          NaN          NaN          NaN          NaN
3          NaN          NaN          NaN          NaN          NaN
4          NaN          NaN          NaN          NaN          NaN

[5 rows x 25 columns]

In [70]:
import pandas as pd
df = pd.read_csv('sheetdsa.csv')
print(df.tail())
# print(df.tail(2))

     Unnamed: 0 Unnamed: 1  Unnamed: 2  \
996         NaN        NaN         NaN
997         NaN        NaN         NaN
998         NaN        NaN         NaN
999         NaN        NaN         NaN
1000        NaN        NaN         NaN

     Do NOT send any edit request to this sheet. Instead, make a copy of your own.  \
996                                                 NaN
997                                                 NaN
998                                                 NaN
999                                                 NaN
1000                                                NaN

     Unnamed: 4 Unnamed: 5 Unnamed: 6 Unnamed: 7 Unnamed: 8  Unnamed: 9  ...  \
996         NaN        NaN        NaN        NaN        NaN         NaN  ...
997         NaN        NaN        NaN        NaN        NaN         NaN  ...
998         NaN        NaN        NaN        NaN        NaN         NaN  ...
999         NaN        NaN        NaN        NaN        NaN         NaN  ...
1000        NaN        NaN        NaN        NaN        NaN         NaN  ...

      Unnamed: 15  Unnamed: 16  Unnamed: 17  Unnamed: 18  Unnamed: 19  \
996           NaN          NaN          NaN          NaN          NaN
997           NaN          NaN          NaN          NaN          NaN
998           NaN          NaN          NaN          NaN          NaN
999           NaN          NaN          NaN          NaN          NaN
1000          NaN          NaN          NaN          NaN          NaN

      Unnamed: 20  Unnamed: 21  Unnamed: 22  Unnamed: 23  Unnamed: 24
996           NaN          NaN          NaN          NaN          NaN
997           NaN          NaN          NaN          NaN          NaN
998           NaN          NaN          NaN          NaN          NaN
999           NaN          NaN          NaN          NaN          NaN
1000          NaN          NaN          NaN          NaN          NaN

[5 rows x 25 columns]

In [71]:
import pandas as pd
df = pd.read_csv('sheetdsa.csv')
print(df.sample())

     Unnamed: 0 Unnamed: 1  Unnamed: 2  \
1000        NaN        NaN         NaN

     Do NOT send any edit request to this sheet. Instead, make a copy of your own.  \
1000                                                NaN

     Unnamed: 4 Unnamed: 5 Unnamed: 6 Unnamed: 7 Unnamed: 8  Unnamed: 9  ...  \
1000        NaN        NaN        NaN        NaN        NaN         NaN  ...

      Unnamed: 15  Unnamed: 16  Unnamed: 17  Unnamed: 18  Unnamed: 19  \
1000          NaN          NaN          NaN          NaN          NaN

      Unnamed: 20  Unnamed: 21  Unnamed: 22  Unnamed: 23  Unnamed: 24
1000          NaN          NaN          NaN          NaN          NaN

[1 rows x 25 columns]

In [72]:
import pandas as pd
df = pd.read_csv('sheetdsa.csv')
print(df.describe())

       Unnamed: 2  Unnamed: 9  Unnamed: 10  Unnamed: 11  Unnamed: 12  \
count  185.000000         0.0          0.0          0.0          0.0
mean     9.486486         NaN          NaN          NaN          NaN
std      6.583996         NaN          NaN          NaN          NaN
min      1.000000         NaN          NaN          NaN          NaN
25%      4.000000         NaN          NaN          NaN          NaN
50%      8.000000         NaN          NaN          NaN          NaN
75%     14.000000         NaN          NaN          NaN          NaN
max     26.000000         NaN          NaN          NaN          NaN

       Unnamed: 13  Unnamed: 14  Unnamed: 15  Unnamed: 16  Unnamed: 17  \
count          0.0          0.0          0.0          0.0          0.0
mean           NaN          NaN          NaN          NaN          NaN
std            NaN          NaN          NaN          NaN          NaN
min            NaN          NaN          NaN          NaN          NaN
25%            NaN          NaN          NaN          NaN          NaN
50%            NaN          NaN          NaN          NaN          NaN
75%            NaN          NaN          NaN          NaN          NaN
max            NaN          NaN          NaN          NaN          NaN

       Unnamed: 18  Unnamed: 19  Unnamed: 20  Unnamed: 21  Unnamed: 22  \
count          0.0          0.0          0.0          0.0          0.0
mean           NaN          NaN          NaN          NaN          NaN
std            NaN          NaN          NaN          NaN          NaN
min            NaN          NaN          NaN          NaN          NaN
25%            NaN          NaN          NaN          NaN          NaN
50%            NaN          NaN          NaN          NaN          NaN
75%            NaN          NaN          NaN          NaN          NaN
max            NaN          NaN          NaN          NaN          NaN

       Unnamed: 23  Unnamed: 24
count          0.0          0.0
mean           NaN          NaN
std            NaN          NaN
min            NaN          NaN
25%            NaN          NaN
50%            NaN          NaN
75%            NaN          NaN
max            NaN          NaN

In [73]:
import pandas as pd
df = pd.read_csv('sheetdsa.csv')
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1001 entries, 0 to 1000
Data columns (total 25 columns):
 #   Column                                                                         Non-Null Count  Dtype
---  ------                                                                         --------------  -----
 0   Unnamed: 0                                                                     13 non-null     object
 1   Unnamed: 1                                                                     186 non-null    object
 2   Unnamed: 2                                                                     185 non-null    float64
 3   Do NOT send any edit request to this sheet. Instead, make a copy of your own.  187 non-null    object
 4   Unnamed: 4                                                                     186 non-null    object
 5   Unnamed: 5                                                                     186 non-null    object
 6   Unnamed: 6                                                                     86 non-null     object
 7   Unnamed: 7                                                                     172 non-null    object
 8   Unnamed: 8                                                                     17 non-null     object
 9   Unnamed: 9                                                                     0 non-null      float64
 10  Unnamed: 10                                                                    0 non-null      float64
 11  Unnamed: 11                                                                    0 non-null      float64
 12  Unnamed: 12                                                                    0 non-null      float64
 13  Unnamed: 13                                                                    0 non-null      float64
 14  Unnamed: 14                                                                    0 non-null      float64
 15  Unnamed: 15                                                                    0 non-null      float64
 16  Unnamed: 16                                                                    0 non-null      float64
 17  Unnamed: 17                                                                    0 non-null      float64
 18  Unnamed: 18                                                                    0 non-null      float64
 19  Unnamed: 19                                                                    0 non-null      float64
 20  Unnamed: 20                                                                    0 non-null      float64
 21  Unnamed: 21                                                                    0 non-null      float64
 22  Unnamed: 22                                                                    0 non-null      float64
 23  Unnamed: 23                                                                    0 non-null      float64
 24  Unnamed: 24                                                                    0 non-null      float64
dtypes: float64(17), object(8)
memory usage: 195.6+ KB
None

In [74]:
import pandas as pd
df = pd.read_csv('sheetdsa.csv')
print(df.dtypes)
print(df.max(numeric_only=True))
print(df.min(numeric_only=True))
print(df.mean(numeric_only=True))

Unnamed: 0                                                                        object
Unnamed: 1                                                                        object
Unnamed: 2                                                                       float64
Do NOT send any edit request to this sheet. Instead, make a copy of your own.     object
Unnamed: 4                                                                        object
Unnamed: 5                                                                        object
Unnamed: 6                                                                        object
Unnamed: 7                                                                        object
Unnamed: 8                                                                        object
Unnamed: 9                                                                       float64
Unnamed: 10                                                                      float64
Unnamed: 11                                                                      float64
Unnamed: 12                                                                      float64
Unnamed: 13                                                                      float64
Unnamed: 14                                                                      float64
Unnamed: 15                                                                      float64
Unnamed: 16                                                                      float64
Unnamed: 17                                                                      float64
Unnamed: 18                                                                      float64
Unnamed: 19                                                                      float64
Unnamed: 20                                                                      float64
Unnamed: 21                                                                      float64
Unnamed: 22                                                                      float64
Unnamed: 23                                                                      float64
Unnamed: 24                                                                      float64
dtype: object
Unnamed: 2     26.0
Unnamed: 9      NaN
Unnamed: 10     NaN
Unnamed: 11     NaN
Unnamed: 12     NaN
Unnamed: 13     NaN
Unnamed: 14     NaN
Unnamed: 15     NaN
Unnamed: 16     NaN
Unnamed: 17     NaN
Unnamed: 18     NaN
Unnamed: 19     NaN
Unnamed: 20     NaN
Unnamed: 21     NaN
Unnamed: 22     NaN
Unnamed: 23     NaN
Unnamed: 24     NaN
dtype: float64
Unnamed: 2     1.0
Unnamed: 9     NaN
Unnamed: 10    NaN
Unnamed: 11    NaN
Unnamed: 12    NaN
Unnamed: 13    NaN
Unnamed: 14    NaN
Unnamed: 15    NaN
Unnamed: 16    NaN
Unnamed: 17    NaN
Unnamed: 18    NaN
Unnamed: 19    NaN
Unnamed: 20    NaN
Unnamed: 21    NaN
Unnamed: 22    NaN
Unnamed: 23    NaN
Unnamed: 24    NaN
dtype: float64
Unnamed: 2     9.486486
Unnamed: 9          NaN
Unnamed: 10         NaN
Unnamed: 11         NaN
Unnamed: 12         NaN
Unnamed: 13         NaN
Unnamed: 14         NaN
Unnamed: 15         NaN
Unnamed: 16         NaN
Unnamed: 17         NaN
Unnamed: 18         NaN
Unnamed: 19         NaN
Unnamed: 20         NaN
Unnamed: 21         NaN
Unnamed: 22         NaN
Unnamed: 23         NaN
Unnamed: 24         NaN
dtype: float64

## 5. DataFrame Selection with `.loc` and `.iloc`

Pandas provides powerful ways to select data using labels (`.loc`) or integer positions (`.iloc`).

Here, we'll demonstrate using a sample DataFrame created locally for clarity.

In [75]:
import pandas as pd
data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 35],
    'City': ['New York', 'San Francisco', 'Los Angeles']
}
df = pd.DataFrame(data)
print(df)
print(df['Name'].min())
print(df['Name'].max())
print(df['Age'].min())
print(df['Age'].max())
print(df['Age'].mean())

      Name  Age           City
0    Alice   25       New York
1      Bob   30  San Francisco
2  Charlie   35    Los Angeles
Alice
Charlie
25
35
30.0

### 5.1 Selecting Columns

In [76]:
import pandas as pd
data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 35],
    'City': ['New York', 'San Francisco', 'Los Angeles']
}
df = pd.DataFrame(data)
print(df['Name'])

0      Alice
1        Bob
2    Charlie
Name: Name, dtype: object

### 5.2 Selecting Rows and Columns by Label (`.loc`)

In [77]:
import pandas as pd
data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 35],
    'City': ['New York', 'San Francisco', 'Los Angeles']
}
df = pd.DataFrame(data)
print(df.loc[2,'Name'])

print(df.loc[0:2,'Name']) # Name wali row ka 0 to 1 wala aa jayega

Charlie
0      Alice
1        Bob
2    Charlie
Name: Name, dtype: object

### 5.3 Selecting Rows and Columns by Integer Position (`.iloc`)

In [78]:
import pandas as pd
data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 35],
    'City': ['New York', 'San Francisco', 'Los Angeles']
}
df = pd.DataFrame(data)

# print(df.iloc[2,2])
# print(df.iloc[1,0])
# print(df.iloc[0,1])

print(df.iloc[0:2,2]) # 2nd row ka 0 to 1 wala aa jayega

0         New York
1    San Francisco
Name: City, dtype: object

## 6. Conditional Selection / Filtering

Filter DataFrames based on conditions applied to one or more columns.

In [79]:
import pandas as pd
data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 35],
    'City': ['New York', 'San Francisco', 'Los Angeles']
}
df = pd.DataFrame(data)

print(df[df['Age'] > 21])

      Name  Age           City
0    Alice   25       New York
1      Bob   30  San Francisco
2  Charlie   35    Los Angeles

## 7. Grouping and Aggregation

Group data based on one or more columns and then apply an aggregation function (like sum, mean, count, etc.) to the groups.

This example uses a local DataFrame for a clear demonstration of `groupby` functionality.

In [80]:
# Grouping And Aggregation

import pandas as pd
data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 35],
    'City': ['New York', 'San Francisco', 'Los Angeles']
}
df = pd.DataFrame(data)

# Group by 'City' and calculate the mean of 'Age' for each city
grouped_by_city_age_mean = df.groupby('City')['Age'].mean()
display(grouped_by_city_age_mean)

# You can also group by 'Age' and see descriptive statistics for other numeric columns if they exist
# For example, if there were another numeric column, say 'Score':
# df_with_score = pd.DataFrame({'Name': ['Alice', 'Bob', 'Charlie'], 'Age': [25, 30, 35], 'Score': [90, 85, 92]})
# grouped_by_age_score_mean = df_with_score.groupby('Age')['Score'].mean()
# display(grouped_by_age_score_mean)

City
Los Angeles      35.0
New York         25.0
San Francisco    30.0
Name: Age, dtype: float64

In [81]:
# Grouping And Aggregation

import pandas as pd
data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 35],
    'City': ['New York', 'San Francisco', 'Los Angeles']
}
df = pd.DataFrame(data)

# Group by 'City' and calculate the mean of 'Age' for each city
grouped_by_city = df.groupby('City')
display(grouped_by_city.size())

City
Los Angeles      1
New York         1
San Francisco    1
dtype: int64